/**
 * DOCX export. Proper headings, paragraph spacing, editable; compatible with Word & Google Docs.
 */
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  PageBreak,
} from "docx";
import type { ExportResult, ExportStoryPayload } from "./types";

export async function exportToDocx(payload: ExportStoryPayload): Promise<ExportResult> {
  const children: Paragraph[] = [];

  // Title page
  children.push(
    new Paragraph({
      text: payload.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 400 },
    })
  );
  if (payload.coverSubtitle) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: payload.coverSubtitle, italics: true })],
        spacing: { after: 200 },
      })
    );
  }
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `${payload.genre.replace(/_/g, " ")} · ${payload.author ?? "Generated by AI"}`,
        }),
      ],
      spacing: { after: 400 },
    })
  );
  if (payload.premise) {
    children.push(
      new Paragraph({
        text: payload.premise,
        spacing: { after: 400 },
      })
    );
  }
  children.push(new Paragraph({ children: [new PageBreak()] }));

  // Chapters: Heading1 for title, then body paragraphs with spacing
  for (const ch of payload.chapters) {
    children.push(
      new Paragraph({
        text: ch.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 320, after: 240 },
      })
    );
    const paragraphs = ch.content
      .split(/\n+/)
      .map((p) => p.trim())
      .filter(Boolean);
    for (const p of paragraphs) {
      children.push(
        new Paragraph({
          text: p,
          spacing: { after: 200 },
        })
      );
    }
  }

  const doc = new Document({
    title: payload.title,
    creator: payload.author ?? "Generated by AI",
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 720,   // 0.5 inch in twips
              right: 720,
              bottom: 720,
              left: 720,
            },
          },
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  const safeTitle = sanitizeFilename(payload.title);

  return {
    buffer,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    fileExtension: "docx",
    suggestedFilename: `${safeTitle}.docx`,
  };
}

function sanitizeFilename(title: string): string {
  return title
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 100) || "story";
}
