/**
 * HTML export. Minimal CSS, semantic tags, readable on mobile and desktop.
 */
import type { ExportResult, ExportStoryPayload } from "./types";

const PAGE_CSS = `
body { font-family: Georgia, 'Times New Roman', serif; font-size: 18px; line-height: 1.6; color: #1a1a1a; max-width: 42em; margin: 0 auto; padding: 1rem 1.5rem; }
h1 { font-size: 2rem; margin-top: 0; border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
h2 { font-size: 1.35rem; margin-top: 2rem; margin-bottom: 0.75rem; }
.subtitle { font-style: italic; color: #555; margin-bottom: 0.5rem; }
.meta { font-size: 0.9rem; color: #666; margin-bottom: 2rem; }
article { margin-top: 2rem; }
.chapter { margin-bottom: 2.5rem; }
.chapter p { margin: 0 0 1rem; text-align: justify; }
@media (max-width: 600px) { body { padding: 1rem; font-size: 16px; } }
`.replace(/\n\s*/g, " ");

export function exportToHtml(payload: ExportStoryPayload): ExportResult {
  const safeTitle = escapeHtml(payload.title);
  const subtitle = payload.coverSubtitle ? `<p class="subtitle">${escapeHtml(payload.coverSubtitle)}</p>` : "";
  const genre = escapeHtml(payload.genre.replace(/_/g, " "));
  const author = escapeHtml(payload.author ?? "Generated by AI");
  const premise = payload.premise ? `<p>${escapeHtml(payload.premise)}</p>` : "";

  const chaptersHtml = payload.chapters
    .map((ch) => {
      const title = escapeHtml(ch.title);
      const paragraphs = ch.content
        .split(/\n+/)
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p) => `<p>${escapeHtml(p)}</p>`)
        .join("\n    ");
      return `  <section class="chapter" aria-label="Chapter ${ch.index + 1}">
    <h2>${title}</h2>
    ${paragraphs}
  </section>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${safeTitle}</title>
  <style>${PAGE_CSS}</style>
</head>
<body>
  <header>
    <h1>${safeTitle}</h1>
    ${subtitle}
    <p class="meta">${genre} · ${author}</p>
    ${premise}
  </header>
  <article>
${chaptersHtml}
  </article>
</body>
</html>`;

  const buffer = Buffer.from(html, "utf-8");
  const safeFilename = sanitizeFilename(payload.title);

  return {
    buffer,
    mimeType: "text/html; charset=utf-8",
    fileExtension: "html",
    suggestedFilename: `${safeFilename}.html`,
  };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function sanitizeFilename(title: string): string {
  return title
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 100) || "story";
}
