/**
 * Story export dispatcher. Builds payload from story document and invokes the right generator.
 */
import type { ExportFormat, ExportResult, ExportStoryPayload } from "./types";
import { exportToTxt } from "./txt";
import { exportToMarkdown } from "./md";
import { exportToHtml } from "./html";
import { exportToPdf } from "./pdf";
import { exportToDocx } from "./docx";

/** Story as returned from MongoDB (lean) or API response shape */
export interface StoryForExport {
  title: string;
  genre: string;
  premise?: string;
  chapterHistory: Array<{ index: number; title: string; content: string }>;
}

export function buildExportPayload(
  story: StoryForExport,
  options?: { author?: string; coverSubtitle?: string }
): ExportStoryPayload {
  return {
    title: story.title,
    genre: story.genre,
    author: options?.author ?? "Generated by AI",
    coverSubtitle: options?.coverSubtitle,
    premise: story.premise,
    chapters: (story.chapterHistory ?? []).map((ch) => ({
      index: ch.index,
      title: ch.title,
      content: ch.content,
    })),
  };
}

export async function exportStory(
  payload: ExportStoryPayload,
  format: ExportFormat
): Promise<ExportResult> {
  switch (format) {
    case "txt":
      return exportToTxt(payload);
    case "md":
      return exportToMarkdown(payload);
    case "html":
      return exportToHtml(payload);
    case "pdf":
      return exportToPdf(payload);
    case "docx":
      return exportToDocx(payload);
    default: {
      const exhaustive: never = format;
      throw new Error(`Unsupported format: ${exhaustive}`);
    }
  }
}

export type { ExportFormat, ExportResult, ExportStoryPayload } from "./types";
