/**
 * Markdown export. # for chapter titles, clean spacing, no HTML.
 */
import type { ExportResult, ExportStoryPayload } from "./types";

export function exportToMarkdown(payload: ExportStoryPayload): ExportResult {
  const lines: string[] = [];

  lines.push(`# ${payload.title}`);
  lines.push("");
  if (payload.coverSubtitle) {
    lines.push(`*${payload.coverSubtitle}*`);
    lines.push("");
  }
  lines.push(`**${payload.genre.replace(/_/g, " ")}** · ${payload.author ?? "Generated by AI"}`);
  if (payload.premise) {
    lines.push("");
    lines.push(payload.premise);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const ch of payload.chapters) {
    lines.push(`## ${ch.title}`);
    lines.push("");
    const paragraphs = ch.content
      .split(/\n+/)
      .map((p) => p.trim())
      .filter(Boolean);
    for (const p of paragraphs) {
      lines.push(p);
      lines.push("");
    }
    lines.push("");
  }

  const text = lines.join("\n").trimEnd();
  const buffer = Buffer.from(text, "utf-8");
  const safeTitle = sanitizeFilename(payload.title);

  return {
    buffer,
    mimeType: "text/markdown; charset=utf-8",
    fileExtension: "md",
    suggestedFilename: `${safeTitle}.md`,
  };
}

function sanitizeFilename(title: string): string {
  return title
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 100) || "story";
}
