/**
 * Plain text export. Clean chapter separation, no markdown symbols.
 */
import type { ExportResult, ExportStoryPayload } from "./types";

export function exportToTxt(payload: ExportStoryPayload): ExportResult {
  const lines: string[] = [];

  lines.push(payload.title.toUpperCase());
  lines.push("");
  if (payload.coverSubtitle) {
    lines.push(payload.coverSubtitle);
    lines.push("");
  }
  lines.push(`${payload.genre.replace(/_/g, " ")}`);
  lines.push(payload.author ?? "Generated by AI");
  lines.push("");
  lines.push("—".repeat(40));
  lines.push("");

  for (const ch of payload.chapters) {
    lines.push(`CHAPTER ${ch.index + 1}: ${ch.title}`);
    lines.push("");
    // Normalize whitespace: collapse multiple newlines, trim each paragraph
    const paragraphs = ch.content
      .split(/\n+/)
      .map((p) => p.trim())
      .filter(Boolean);
    for (const p of paragraphs) {
      lines.push(p);
      lines.push("");
    }
    lines.push("");
  }

  const text = lines.join("\n").trimEnd();
  const buffer = Buffer.from(text, "utf-8");
  const safeTitle = sanitizeFilename(payload.title);

  return {
    buffer,
    mimeType: "text/plain; charset=utf-8",
    fileExtension: "txt",
    suggestedFilename: `${safeTitle}.txt`,
  };
}

function sanitizeFilename(title: string): string {
  return title
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 100) || "story";
}
