/**
 * Types for story export. Used by all format generators.
 */

export interface ExportChapter {
  index: number;
  title: string;
  content: string;
}

export interface ExportStoryPayload {
  title: string;
  genre: string;
  /** Default: "Generated by AI" */
  author?: string;
  /** Optional subtitle for cover/title page */
  coverSubtitle?: string;
  premise?: string;
  chapters: ExportChapter[];
}

export type ExportFormat = "pdf" | "docx" | "txt" | "md" | "html";

export interface ExportResult {
  buffer: Buffer;
  mimeType: string;
  fileExtension: string;
  suggestedFilename: string;
}
